Mod/tor/fix issues
pegasystems/react-sdk-components pull request #236
Opened 2023-11-09 21:14 UTC by vishalshrm539

* Fixed ToDo, etc. issues and laywright tests.

2023-11-10 11:50 UTC, tumms2021389 requested changes

2023-11-10 11:50 UTC, tumms2021389 commented on package.json
> +    "compare-versions": "^6.1.0",
can't we just write our custom logic to compare versions instead of new package?

2023-11-10 11:50 UTC, tumms2021389 commented on packages/react-sdk-components/src/components/widget/Attachment/Attachment.tsx
> +  const is884OrBetter = compareVersions(PCoreVersion, '8.8.3') === 1;
change this name to "is884OrHigher"

2023-11-10 11:50 UTC, tumms2021389 commented on packages/react-sdk-components/src/components/widget/Attachment/Attachment.tsx
> +    PCore.getStateUtils().updateState(pConn.getContextName(), getAttachmentKey(is884OrBetter ? valueRef : ''), undefined, {
Also, it is better to have a new variable to store this value and use that variable in all places instead of repeating same code everywhere

2023-11-10 11:56 UTC, vishalshrm539 commented on package.json
> +    "compare-versions": "^6.1.0",
Comparing versions isn't a trivial task hence opted for this.

2023-11-10 11:57 UTC, vishalshrm539 commented on packages/react-sdk-components/src/components/widget/Attachment/Attachment.tsx
> +    PCore.getStateUtils().updateState(pConn.getContextName(), getAttachmentKey(is884OrBetter ? valueRef : ''), undefined, {
Makes sense. Will update.

2023-11-10 14:10 UTC, niallriddell approved these changes
Tested using test:headed and passed using 5304

2023-11-13 15:24 UTC, vrseraphin commented on package.json
> +    "compare-versions": "^6.1.0",
Have never been a fan of checking specific version numbers (preferring "capability" checking....looking for existence of some specific API or constant).  This then would work much smoother when such "capability" is added back to earlier patch releases.

2023-11-20 07:41 UTC, vishalshrm539 commented on package.json
> +    "compare-versions": "^6.1.0",
Unfortunately, checking for existence of an API, etc. won't work here since the issue is not whether we've an API or not but rather the difference here is in passing a parameter.

2023-11-20 07:44 UTC, tumms2021389 approved these changes

2023-11-20 07:45 UTC, merged