refresh of view not happening issue fixed
pegasystems/react-sdk-components pull request #263
Opened 2023-12-29 09:58 UTC by 4manasa

2023-12-29 10:43 UTC, tumms2021389 requested changes

2023-12-29 10:43 UTC, tumms2021389 commented on packages/react-sdk-components/src/components/infra/Containers/SimpleView/helper.ts
> +};
Keep this function in common helper.ts file for Containers

2023-12-29 11:16 UTC, 4manasa commented on packages/react-sdk-components/src/components/infra/Containers/SimpleView/helper.ts
> +};
> Keep this function in common helper.ts file for Containers

Done

2024-01-02 19:07 UTC, tumms2021389 approved these changes
All tests are passing except Inline Dashboard (issue is not related to these changes)

2024-01-02 19:22 UTC, paulgagnon-pega approved these changes

2024-01-03 06:04 UTC, merged