Fix typing isues with latest typedefs
pegasystems/react-sdk-components pull request #285
Opened 2024-02-13 10:24 UTC by vishalshrm539

* Fixed typing issues that came up with latest typedefs.

2024-02-13 15:26 UTC, paulgagnon-pega submitted a review, later dismissed

2024-02-13 16:18 UTC, tumms2021389 requested changes

2024-02-13 16:18 UTC, tumms2021389 commented on package.json
> +    "pack-overrides": "npm  pack ./packages/react-sdk-overrides",
What is the need of this script? Let's not have too many scripts

2024-02-13 16:18 UTC, tumms2021389 commented on package.json
> +    "pack-overrides": "npm  pack ./packages/react-sdk-overrides",
Lets remove it for now, we can check this later

2024-02-13 16:41 UTC, vishalshrm539 commented on package.json
> +    "pack-overrides": "npm  pack ./packages/react-sdk-overrides",
We already have a similar script for packing the SDK(i.e. pack-sdk) so can have similiar for overrides I believe.

2024-02-14 05:49 UTC, tumms2021389 commented on package.json
> +    "pack-overrides": "npm  pack ./packages/react-sdk-overrides",
pack-sdk doesn't give any meaning to me, lets remove the scripts for packing from package.json as we don't run them more often and our document already has the steps for packaging the components and overrides

2024-02-14 07:40 UTC, vishalshrm539 commented on package.json
> +    "pack-overrides": "npm  pack ./packages/react-sdk-overrides",
Ok, got rid of both.

2024-02-14 08:48 UTC, tumms2021389 approved these changes

2024-02-14 08:52 UTC, merged