Fix InlineDashboard test
pegasystems/react-sdk-components pull request #302
Opened 2024-03-22 14:00 UTC by samhere06

Fix failing InlineDashboard test

2024-03-25 11:59 UTC, tumms2021389 requested changes

2024-03-25 11:59 UTC, tumms2021389 commented on packages/react-sdk-components/tests/e2e/Digv2/LandingPages/InlineDashboard.spec.js
> +    await responsePromise;
change this to 
`await page.waitForResponse('**/data_views/D_ComplexFieldsList')`

2024-03-26 10:40 UTC, samhere06 commented on packages/react-sdk-components/tests/e2e/Digv2/LandingPages/InlineDashboard.spec.js
> +    await responsePromise;
updated with change

2024-03-26 10:47 UTC, tumms2021389 requested changes

2024-03-26 10:47 UTC, tumms2021389 commented on packages/react-sdk-components/tests/e2e/Digv2/FormFields/OptionalAction.spec.js
> +  let attributes;
you can remove attributes variable from here

2024-03-26 10:57 UTC, samhere06 commented on packages/react-sdk-components/tests/e2e/Digv2/FormFields/OptionalAction.spec.js
> +  let attributes;
updated with change

2024-03-26 11:03 UTC, tumms2021389 approved these changes

2024-03-26 11:13 UTC, merged