Display currency symbol in decimal
pegasystems/react-sdk-components pull request #323
Opened 2024-04-10 11:42 UTC by samhere06

Updated decimal component. when decimal is read only and displayed as currency, no currency symbol was displayed. After this change will be able to see currency symbol in UI.

2024-04-10 11:47 UTC, tumms2021389 commented
Making this PR as a WIP PR, will review and merge this PR once release is done

2024-04-15 18:25 UTC, tumms2021389 commented
@samhere06 , 

Decimal component is showing currency symbol in editable mode as well

![image](https://github.com/pegasystems/react-sdk-components/assets/97188066/71458252-c8c0-4d70-a64d-1925e53f5a56)

It should show currency symbol only when it is configured as ReadOnly currency field

2024-04-15 18:26 UTC, tumms2021389 requested changes
Requesting changes

2024-04-16 06:41 UTC, samhere06 commented
> @samhere06 ,
> 
> Decimal component is showing currency symbol in editable mode as well
> 
> ![image](https://private-user-images.githubusercontent.com/97188066/322587935-71458252-c8c0-4d70-a64d-1925e53f5a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDk5MzgsIm5iZiI6MTcxMzI0OTYzOCwicGF0aCI6Ii85NzE4ODA2Ni8zMjI1ODc5MzUtNzE0NTgyNTItYzhjMC00ZDcwLWE2NGQtMTkyNWU1M2Y1YTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA2NDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMjEwNmI5ZDE0MWIxZmQ0NTc2MTk0Y2YwYjJmZjI0MTUwMWU1NzNiZWZhMGIxZTM3MDc3MTk4MDIwYmM4ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GDkaeuXAV2_3Vwv4JqWEAp08T6DRYK7SGwn1RQmH69o)
> 
> It should show currency symbol only when it is configured as ReadOnly currency field

Made this change and added test

2024-04-18 19:40 UTC, tumms2021389 approved these changes
Looks good to me

2024-04-19 04:31 UTC, merged