Added multiselect combobox support into React SDK
pegasystems/react-sdk-components pull request #328
Opened 2024-04-15 18:21 UTC by 4manasa

2024-04-17 12:51 UTC, paulgagnon-pega submitted a review, later dismissed

2024-04-18 19:24 UTC, tumms2021389 requested changes

2024-04-18 19:24 UTC, tumms2021389 commented on packages/react-sdk-components/src/components/field/Multiselect/Multiselect.tsx
> +  const { doSearch, getDisplayFieldsMetaData, useDeepMemo, preProcessColumns, getGroupDataForItemsTree } = utils;
why don't you restructure these methods in the import statement itself?

2024-04-18 19:24 UTC, tumms2021389 commented on packages/react-sdk-components/src/components/field/Multiselect/Multiselect.tsx
> +  const checkedIcon = <CheckBoxIcon fontSize='small' />;
You can move constants out of react component

2024-04-18 19:24 UTC, tumms2021389 commented on packages/react-sdk-components/src/components/field/Multiselect/Multiselect.tsx
> +        selectedRows.length > 0
I dont understand this ternary condition clearly, Why you are checking the length here

2024-04-19 13:36 UTC, 4manasa commented on packages/react-sdk-components/src/components/field/Multiselect/Multiselect.tsx
> +        selectedRows.length > 0
I'm iterating through the selectedRows to create a map in the expected format for the combobox component. Before the iteration, I'm checking if selectedRows contains any records by verifying its length.

2024-04-19 13:53 UTC, 4manasa commented on packages/react-sdk-components/src/components/field/Multiselect/Multiselect.tsx
> +  const checkedIcon = <CheckBoxIcon fontSize='small' />;
Done

2024-04-19 13:53 UTC, 4manasa commented on packages/react-sdk-components/src/components/field/Multiselect/Multiselect.tsx
> +  const { doSearch, getDisplayFieldsMetaData, useDeepMemo, preProcessColumns, getGroupDataForItemsTree } = utils;
Done

2024-04-22 19:00 UTC, tumms2021389 requested changes

2024-04-22 19:00 UTC, tumms2021389 commented on packages/react-sdk-components/src/components/field/Multiselect/Multiselect.tsx
> +        selectedRows.length > 0
If selectedRows is already an array then you can directly run .map method on it, you dont have to check the length

2024-04-22 19:00 UTC, tumms2021389 commented on packages/react-sdk-components/src/components/field/Multiselect/Multiselect.tsx
> +        selectedRows.length > 0
[].map(item => ...) returns [] only, you dont have to check the length if you are running map on array. 

May be you can check whether selectedRows exists or undefined

2024-04-23 07:48 UTC, tumms2021389 approved these changes
Changes looks good to me

2024-04-23 08:07 UTC, merged